<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net9.0-windows10.0.26100.0;net10.0-windows10.0.26100.0</TargetFrameworks>
		<OutputType>Library</OutputType>
		<UseUwp>true</UseUwp>
		<DisableRuntimeMarshalling>true</DisableRuntimeMarshalling>
		<DefineConstants>WIN_UWP</DefineConstants>
	</PropertyGroup>
	
	<PropertyGroup>
		<PackageId>ImageEx.UWP</PackageId>
		<PackageReleaseNotes>
			Version 5.0
			- .NET 10.0 TFM
			- Updated package structure (without xbf files)
		</PackageReleaseNotes>
		<PackageIcon>UWPLogo.png</PackageIcon>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\UWPLogo.png" Pack="true" PackagePath="\" />
		<None Include="..\README.md" Pack="true" PackagePath="\" />
	</ItemGroup>
	
</Project>